//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace madurativas.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class estudio
    {
        public System.DateTime fechaestudio { get; set; }
        public string digitado { get; set; }
        public bool activo { get; set; }
        public decimal pacienteid { get; set; }
        public long estudioId { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual eval_riesgos eval_riesgos { get; set; }
        public virtual mchat mchat { get; set; }
    }
}
