//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace madurativas.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class hitos_area_social
    {
        public int hito_social_id { get; set; }
        public string descripcion { get; set; }
        public decimal min { get; set; }
        public decimal max { get; set; }
    }
}
